pthread.o: pthread.cc /home/ugb/tttakaha/kos/src/ulib/../testoptions.h \
 /home/ugb/tttakaha/kos/src/ulib/../include/syscalls.h \
 /home/ugb/tttakaha/kos/src/ulib/../include/kostypes.h \
 /home/ugb/tttakaha/kos/src/ulib/../include/pthread.h \
 /home/ugb/tttakaha/kos/src/ulib/../include/syscalls.h
libKOS.o: libKOS.cc /home/ugb/tttakaha/kos/src/ulib/../testoptions.h \
 /home/ugb/tttakaha/kos/src/ulib/../include/syscalls.h \
 /home/ugb/tttakaha/kos/src/ulib/../include/kostypes.h
